### ISSUE TITLE
Incorrect CVE status for 16.04 ESM

### ISSUE THREAD

**Issue by alexmurray** [canonical-web-and-design/ubuntu-com-security-api#49]
## Summary

Currently the web view shows for say https://ubuntu.com/security/CVE-2020-15180 that the status for say mariadb-10.0 for 16.04 ESM is 'Ignored (end of standard support, was needs-triage)' - this is incorrect, as can be seen in the CVE tracker git repo at https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2020-15180#n25 - as that is the status for 16.04 LTS - and there is no current status for 16.04 ESM. The security team plans to add an additional field to each CVE to track the status of CVEs for 16.04 ESM and so once this is done this should be used instead.

Similarly, for the recently announced exim4 CVEs, taking https://ubuntu.com/security/CVE-2020-28024 as an example, this shows ignored for 16.04 ESM - and this is creating a lot of confusion amongst customers, as the real status for this CVE is needs-triage (https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2020-28024#n26)

## Process

Compare web view to the CVE tracker git.

## Current and expected result

The status should match that which is in the CVE files in the git CVE tracker.

**Comment by albertkol** [comment]
@alexmurray @stevebeattie @nottrobin 

I am trying to figure out how to approach this issue.

Right now what happens on prod. Everywhere we displayed 16.04 LTS shows now 16.04 ESM. The logic behind is very simple, it's an `if` that checks the date in the database and determines the support tag to use (LTS or ESM). This will be applied to past and future CVEs, USNs and LSNs.

We do not have a separate entry in the table to display the statuses for both 16.04 LTS and 16.04 ESM.

My understanding is that once a release transitions to ESM, we would only show the status in ESM, and let the user know that the fix is available only in UA for infra and/or UA for App.

So would a potential fix to this issue be to instead of having `Ignored (end of standard support, was needs-triage)` in 16.04 ESM to have the status `needs-triage` (or whatever it is), marked as available in `esm-app` or `esm-infra`?

If this is not a good enough solution, we might have to have a meeting and discuss how to properly address this.

**Comment by albertkol** [comment]
This is very old. Closing. If it's still a problem, please re-open.
